apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sharelatexdeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sharelatex
    spec:
      containers:
      - name: sharelatexcontainer
        image: sharelatex/sharelatex
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: SHARELATEX_MONGO_URL
            value: "mongodb://mongo/sharelatex"
          - name: SHARELATEX_REDIS_HOST
            value: "redis"
          - name: SHARELATEX_APP_NAME
            value: "Our ShareLaTeX"
