apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: mongo
  labels:
    app: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    name: mongo
    targetPort: 27017
    nodePort: 32756
  selector:
    app: mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongocontainer
        image: mongo:2.6
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
