apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    name: redis
    targetPort: 6379
    nodePort: 32757
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redisdeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: rediscontainer
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379

