apiVersion: v1
kind: Pod
metadata:
  name: sharelatex
  labels:
    app: sharelatexShare
spec:
  containers:
    - name: share
      image: sharelatex/sharelatex
      ports:
        - containerPort: 80
      env:
      - name: SHARELATEX_MONGO_URL
        value: "mongodb://mongo/sharelatex"
      - name: SHARELATEX_REDIS_HOST
        value: "redis"
      - name: SHARELATEX_APP_NAME
        value: "Our ShareLaTeX"
