apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: nodejs
  labels:
    app: nodejs
spec:
  type: NodePort
  ports:
  - port: 8095
    name: nodejs
    targetPort: 8095
    nodePort: 32758
  selector:
    app: nodejs

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejsdeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejscontainer
        image: yanlibert/node-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8095
